### ISSUE TITLE
Exercises TODO

### ISSUE THREAD

**Issue by bbarker** [bbarker/SoftwareTools#2]
These aren't things we necessarily need to do but it is helpful to have a list of things not yet done that are in the book.

- [ ] 1-5, p 18: Word count: sentences
- [ ] `getc` and `putc` (and related exercises) on pp 31-32
- [ ] `getarg` p 38
- [ ] ex 2-4 and 2-5 on p 39 (see #7) 
- [ ] overstrikes on pp 39-41 (this is a very niche application nowadays, mostly useful for typewriter-like printers)
